version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    restart: unless-stopped

    ports:
      - "8123:8123" # HTTP interface
      - "9000:9000" # Native TCP client protocol

    volumes:
      # Bind mount for ClickHouse data persistence
      - ~/docker_container_storage/clickhouse/data:/var/lib/clickhouse
      # Bind mount for ClickHouse logs persistence
      - ~/docker_container_storage/clickhouse/logs:/var/log/clickhouse-server
      # Bind mount for the custom listen_host configuration
      - ~/docker_container_storage/clickhouse/config/listen.xml:/etc/clickhouse-server/config.d/listen.xml:ro # 'ro' for read-only

    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: "YourStrongSecurePasswordHere" # IMPORTANT: REPLACE THIS!
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1

    ulimits:
      nofile:
        soft: 262144
        hard: 262144

    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK

    networks:
      - server_default_network # Attach this service to the shared network

# Define the shared network as external at the top level
networks:
  server_default_network:
    external: true # This tells Docker Compose that the network already exists
